config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :todos
  end
  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  accepts_nested_attributes_for :user, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,
            presence: true
  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: /\A\S+@.+\.\S+\z/,
                      message: 'Please enter a correct email' }
  has_many :todo, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def show
    @todo = Todo.find(todo_params)
    @user = User.find(params[:user_id])
  end

  def new
    @todo = Todo.new
    @user = User.find(params[:user_id])
  end

  def create
    @todo = Todo.new(todo_params)
    @user = User.find(params[:user_id])
    @todo.user = @user
    if @todo.save
      redirect_to user_path(@user, @todo)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @todo = Todo.find(params[:id])
    @todo.user = @user
  end

  def update
    @todo = Todo.find(params[:id])
    @user = User.find(params[:user_id])
    @todo.user = @user
    @todo.update(todo_params)
    redirect_to user_path(@user)
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to user, satus: :see_other
  end

  private

  def todo_params
    params.require(:todo).permit(:task_name, :status, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @todos = Todo.all
  end

  def show
    @user = User.find(params[:id])
    @todo = @user.todo
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, satus: :see_other
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NetendersTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= simple_form_for([@user, @todo]) do |f| %>
  <%= f.input :task_name %>
  <%= f.input :status, collection: [ "todo", "doing", "done" ] %>
  <%= f.submit %>
<% end %>

app/views/todos/edit.html.erb
<h1> Edit the task </h1>

<%= render "form", todo: @todo %>

<%= link_to "Cancel", user_path(@user) %>

app/views/todos/new.html.erb
<h1>Create a new task for</h1>

<%= simple_form_for([@user, @todo]) do |f| %>
  <%= f.input :task_name %>
  <%= f.input :status, priority: [ "todo" ], collection: [ "todo", "doing", "done" ] %>
  <%= f.submit %>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit <%= @user.name %></h1>

<%= render "form", user: @user %>

<%= link_to "Back to the user", user_path(@user) %>

app/views/users/index.html.erb
<h1>All users</h1>

<div class="divTable">
  <div class="divTableBody">
    <div class="divTableRow">
      <div class="divTableCell"><b>User</b></div>
      <div class="divTableCell"><b>To-dos count</b></div>
    </div>
  <% @users.each do |user| %>
    <div class="divTableRow">
      <div class="divTableCell"><%= link_to user.name, user_path(user)  %></div>
      <div class="divTableCell"><%= user.todo.count %></div>
    </div>
  <% end %>
  </div>
</div>

<a href="/users/new/">Add a new user</a>

app/views/users/new.html.erb
<h1>Create a new user</h1>

<%= render "form", user: @user %>

<%= link_to "Go back to the main page", users_path %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

Tasks to do by <%= @user.name %>:<br>

<div class="divTable">
  <div class="divTableBody">
    <div class="divTableRow">
      <div class="divTableCell"><b>Task</b></div>
      <div class="divTableCell"><b>Status</b></div>
    </div>
  <% @todo.each do |todo| %>
    <div class="divTableRow">
      <div class="divTableCell"><%= todo.task_name %></div>
      <div class="divTableCell"><%= todo.status %><%= link_to edit_user_todo_path(@user, todo) do %><i class="bi bi-pencil"></i>  <% end %></div>
    </div>
  <% end %>
  </div>
</div>
<%= link_to "Add a new task for #{@user.name}", new_user_todo_path(@user) %><br>
<%= link_to "Edit user", edit_user_path(@user) %> |
<%= link_to "Delete user",
  user_path(@user),
  data: { method: :delete, confirm: "Are you sure?" }
%><br>
<a href="/">Go back to the main page </a>